name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ['1.16.2']
    name: Test with Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          stable: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

      - name: go vet
        run: |
          go vet -tags=example -v ./...

      - name: go build
        run: |
          go build -tags=example -v ./...
          env GOOS=js GOARCH=wasm go build .

      - name: go test
        run: |
          go test -v ./...